[tool.poetry]
name = "yepcord-server"
version = "1.0.0b2"
description = "YEPCord - Free open source selfhostable fully discord-compatible chat"
authors = ["RuslanUC <dev_ruslan_uc@protonmail.com>"]
license = "AGPL-3.0"
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.9"
quart = "0.18.4"
aiofiles = "23.2.1"
jinja2 = "3.1.2"
websockets = "11.0.3"
uvicorn = "0.23.2"
aiohttp = "3.8.6"
python-magic = "0.4.27"
pillow = "10.0.1"
protobuf = "4.23.4"
schema = "0.7.5"
python-dateutil = "2.8.2"
cryptography = "41.0.4"
emoji = "2.8.0"
pytest = "7.4.0"
pytest-asyncio = "0.21.1"
six = "1.16.0"
bcrypt = "4.0.1"
quart-schema = "0.16.0"
pydantic = "1.10.8"
types-protobuf = "4.23.0.2"
werkzeug = "2.3.6"
aioftp = "0.21.4"
aioboto3 = ">=11.2.0,<11.3.0"
botocore = ">=1.29.76,<1.30.0"
protobuf-to-dict = {git = "https://github.com/yepcord/protobuf-to-dict"}
ormar = {git = "https://github.com/yepcord/ormar"}
orjson = "3.9.2"
aiomysql = "0.2.0"
pymysql = ">=0.9"
aiosqlite = ">=0.17,<0.20"
databases = "0.6.2"
SQLAlchemy = "1.4.41"
alembic = "1.11.2"
mailers = {version = "3.0.1", extras = ["smtp"]}
propan = {version = "0.1.5.24", extras = ["async-rabbit", "async-redis"]}
redis = ">=4.6.0"
click = "8.1.7"
maxminddb = ">=2.4.0,<2.5.0"
wget = "3.2"

[tool.poetry.group.dev.dependencies]
pytest = "7.4.0"
pytest-cov = "4.1.0"
pytest-asyncio = "0.21.1"
fake-s3 = "1.0.1"
pyftpdlib = "1.5.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
