[tool.poetry]
name = "yepcord-server"
version = "1.0.0b2"
description = "YEPCord - Free open source selfhostable fully discord-compatible chat"
authors = ["RuslanUC <dev_ruslan_uc@protonmail.com>"]
license = "AGPL-3.0"
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.9"
quart = "0.19.3"
aiofiles = "23.2.1"
jinja2 = "3.1.2"
websockets = "12.0"
uvicorn = "0.23.2"
aiohttp = "3.9.0b0"
python-magic = "0.4.27"
pillow = "10.1.0"
protobuf = "4.23.4"
python-dateutil = "2.8.2"
cryptography = "41.0.4"
emoji = "2.8.0"
pytest-asyncio = "0.21.1"
six = "1.16.0"
bcrypt = "4.0.1"
quart-schema = "0.17.1"
pydantic = "2.4.2"
types-protobuf = "4.23.0.2"
werkzeug = "3.0.0"
aioftp = "0.21.4"
aioboto3 = "11.3.1"
botocore = "1.31.17"
protobuf-to-dict = {git = "https://github.com/yepcord/protobuf-to-dict"}
orjson = "3.9.9"
mailers = {version = "3.0.1", extras = ["smtp"]}
propan = {version = "0.1.5.24", extras = ["async-rabbit", "async-redis"]}
redis = ">=4.6.0"
click = "8.1.7"
maxminddb = ">=2.4.0,<2.5.0"
wget = "3.2"
tortoise-orm = {extras = ["asyncmy"], version = "^0.20.0"}
uvloop = "0.19.0"
async-timeout = "^4.0.3"

[tool.poetry.group.dev.dependencies]
pytest-cov = "4.1.0"
pytest-asyncio = "0.21.1"
fake-s3 = "1.0.1"
pyftpdlib = "1.5.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
